CREATE TABLE Setup.InsurancePayment(
	RowId						INT					IDENTITY(1,1),
	KYCCode						VARCHAR(30)			NULL,
	Province					VARCHAR(150)		NULL,
	VechicleCategory			VARCHAR(150)		NULL,
	CompanyName					VARCHAR(150)		NULL,
	InsuranceRate				VARCHAR(150)		NULL,
	PaidDate					VARCHAR(150)		NULL,
	CreatedBy					VARCHAR(150)		NULL,
	CreatedDate					DATETIME			NULL,
	ModifiedBy					VARCHAR(150)		NULL,
	ModifiedDate				DATETIME			NULL,
	VerifiedBy					VARCHAR(150)		NULL,
	VerifiedDate				DATETIME			NULL,
	VerifiedRemarks				VARCHAR(MAX)		NULL,
	ApprovedBy					VARCHAR(150)		NULL,
	ApprovedDate				DATETIME			NULL,
	ApprovedRemarks				VARCHAR(MAX)		NULL
)